sudo: false
language: python
cache:
  directories:
      - $HOME/virtualenv/python2.7.9
python:
  - "2.7"
services:
  - postgresql
addons:
  - postgresql: "11.5"
before_script:
  # Check imports
  - isort --check-only --diff --quiet
  # Check flake8
  - flake8 drivetracker
  - "export DATABASE_URL=postgres://postgres@localhost:5432/drivetracker"
  - psql -c 'create database drivetracker;' -U postgres
  - "python manage.py collectstatic --no-input"
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24"
  - sleep 3
branches:
  only:
    - master
    - develop
install: "pip install -r requirements.txt"
script: "coverage run --source=drivetracker manage.py test --keepdb"
after_success: coveralls
