# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 23:48
from __future__ import unicode_literals

from django.db import migrations, models

import drivetracker.drives.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardDrive',
            fields=[
                ('id', models.BigIntegerField(default=drivetracker.drives.models.generate_id, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('capacity', models.IntegerField(blank=True)),
                ('capacity_unit', models.CharField(blank=True, max_length=3)),
                ('media_type', models.CharField(blank=True, choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('SSHD', 'SSHD')], max_length=4)),
                ('interface', models.CharField(blank=True, choices=[('IDE', 'IDE'), ('SATA', 'SATA'), ('SAS', 'SAS'), ('USB', 'USB'), ('FW', 'FireWire'), ('TB', 'Thunderbolt'), ('PCIE', 'PCIe')], max_length=4)),
                ('form_factor', models.CharField(blank=True, choices=[('1.8', '1.8"'), ('2.5', '2.5"'), ('3.5', '3.5"')], max_length=3)),
                ('rpm', models.IntegerField(blank=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('in_use', models.BooleanField()),
                ('status', models.BooleanField()),
                ('purchase_date', models.DateTimeField(blank=True)),
                ('warranty_date', models.DateTimeField(blank=True)),
                ('service_start_date', models.DateTimeField(blank=True)),
                ('service_end_date', models.DateTimeField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
