# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harddrive',
            name='rpm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
