# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_alter_rpm_to_be_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harddrive',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
