# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0004_all_all_fields_to_be_nullable_or_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harddrive',
            name='capacity_unit',
        ),
        migrations.AlterField(
            model_name='harddrive',
            name='capacity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
