# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0005_convert_capacities_to_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harddrive',
            name='host',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
