# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 19:05
from __future__ import unicode_literals

from django.db import migrations


def copy_data_to_new_models(apps, schema_editor):
    HardDrive = apps.get_model('drives', 'HardDrive')
    Host = apps.get_model('drives', 'Host')
    Manufacturer = apps.get_model('drives', 'Manufacturer')
    Model = apps.get_model('drives', 'Model')

    for hd in HardDrive.objects.all():
        Host.objects.get_or_create(name=hd.host)
        Manufacturer.objects.get_or_create(name=hd.manufacturer)
        Model.objects.get_or_create(name=hd.model)


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0007_creating_models_autocomplete'),
    ]

    operations = [
        migrations.RunPython(copy_data_to_new_models, ),
    ]
