# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0008_migrating_data_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='harddrive',
            name='host_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drives.Host'),
        ),
        migrations.AddField(
            model_name='harddrive',
            name='manufacturer_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drives.Manufacturer'),
        ),
        migrations.AddField(
            model_name='harddrive',
            name='model_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drives.Model'),
        ),
    ]
