# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 19:05
from __future__ import unicode_literals

from django.db import migrations


def link_up_new_models(apps, schema_editor):
    HardDrive = apps.get_model('drives', 'HardDrive')
    Host = apps.get_model('drives', 'Host')
    Manufacturer = apps.get_model('drives', 'Manufacturer')
    Model = apps.get_model('drives', 'Model')

    for hd in HardDrive.objects.all():
        hd.host_new = Host.objects.get(name=hd.host)
        hd.manufacturer_new = Manufacturer.objects.get(name=hd.manufacturer)
        hd.model_new = Model.objects.get(name=hd.model)
        hd.save()


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0009_creating_new_foreignkeys_new_models'),
    ]

    operations = [
        migrations.RunPython(link_up_new_models, ),
    ]
