# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0012_remove_dupes_new_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
