# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0013_enforce_name_uniqueness_for_new_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harddrive',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='harddrive',
            name='service_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='harddrive',
            name='service_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='harddrive',
            name='warranty_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
